# Generated by Django 4.0.1 on 2022-01-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['date_added'], 'verbose_name_plural': 'diaries'},
        ),
    ]
